---
apiVersion: v1
kind: ReplicationController
metadata:
  name: flask
spec:
  replicas: 2
  selector:
    app: flask
  template:
    metadata:
      name: flask
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: mateobur/trivial-flask
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: "app"
          mountPath: "/app/app.py"
          subPath: "app.py"
      volumes:
        - name: "app"
          configMap:
            name: "flaskapp"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: flask
  name: flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
  - name: http
    port: 5000
    targetPort: 5000
      
